// This file was auto-generated based on version 1.1.0 of the canonical data.

using System;
using System.Diagnostics;
using Xunit;

public class ScrabbleScoreTest
{
    [Fact]
    public void Perfomance()
    {
        string testBigText = @"If	you’ve	picked	up	this	book,	chances	are	you’ve	wanted	to	speak	English	for	a while.	Maybe	you’ve	even	taken	classes.	You	probably	need	English	to	improve your	career.	Maybe	you	want	to	travel	internationally	or	study	abroad.	You	know that	English	is	the	key	to	international	business	and	international	travel.	So	let	me ask	you	something. Do	you	feel	nervous	or	shy	when	you	try	to	speak	English?	Do	you	still	struggle to	understand	what	someone	is	saying	to	you	despite	years	of	study?	Are	you embarrassed	about	your	pronunciation	or	worried	you	speak	too	slowly?	Are	you frustrated	that	despite	all	the	time	you’ve	invested	in	learning	English	you	still	can’t speak	it?	Despite	your	goals,	is	it	difficult	for	you	to	actually	use	English	in	your job,	travels,	or	studies?	Do	you	sometimes	feel	that	you’ll	never	master	spoken English? If	you	answered	yes	to	any	of	these	questions,	you’re	not	alone.	In	fact,	you’re fairly	typical.	Most	English	students	feel	this	way.	Most	adult	English	learners	are stressed	and	frustrated	about	their	speaking	ability.	Some	feel	completely	hopeless and	feel	they’ll	never	be	able	to	speak	English	powerfully.	Not	because	they’re	bad at	languages,	but	because,	like	you,	they’ve	been	taught	using	the	wrong	methods. The	good	thing	is	that	it	doesn’t	have	to	be	like	this.	There	is	nothing	wrong	with you.	You	can	learn	to	speak	English	naturally	and	with	ease.	You	can	use	English effectively	in	your	job,	travels,	and	studies.	You	can	feel	relaxed	and	confident every	time	you	speak	English.	In	fact,	as	a	long-time	English	teacher,	I’ve	helped thousands	of	students	all	over	the	world	become	fluent	and	powerful	English
speakers. How	did	I	do	it?	I	did	it	using	a	teaching	method	I	developed	called	Effortless English™.	Effortless	English™	enables	you	to	learn	English	naturally	and automatically	–	the	way	children	learn	before	they	enter	school.	Too	often,	English classes	get	so	focused	on	tests,	textbooks,	grades	and	“levels,”	students	forget	why they’re	there	in	the	first	place.	They	forget	about	the	real	world	goals	of	a	more successful	career	and	exciting	international	travel.	With	Effortless	English™	you never	lose	sight	of	the	fact	that	the	ultimate	goal	of	learning	a	language	is communication.	Instead,	you	learn	to	speak	English	both	quickly	and	with	more precision.
Effortless? I	understand	if	you’re	skeptical	–	particularly	if	you’ve	been	trying	to	learn	English the	traditional	way.	You’ve	put	in	the	hours:	memorizing	vocabulary	lists,	doing grammar	drills,	reading	boring	textbooks.	“How?”	you’re	thinking,	“can	speaking English	possibly	be	effortless?” Believe	me,	I	feel	your	pain. Back	when	I	started	teaching	15	years	ago,	my	students	were	all	excited	to	begin conversing	in	English.	And	I	was	excited	to	help	them.	At	that	time,	I	taught	in	the usual	way.	I	used	textbooks	and	I	focused	on	teaching	grammar.	I	thought	this	was the	best	way	to	teach,	and	none	of	my	students	complained. I	still	remember	one	particularly	intelligent	student	of	mine	from	Venezuela named	Gladys.	Gladys	was	determined	to	speak	English	well.	Talk	about	effort! Gladys	attended	every	one	of	my	classes.	She	always	sat	in	the	center	of	the	front row.	I	can	still	picture	her	eager	and	smiling	face.	She	took	detailed	notes.	She listened	to	every	word	I	said.	She	also	studied	at	home.	Every	day	Gladys	studied
her	English	textbooks	for	four	hours	or	more.	She	also	tried	to	learn	50	new vocabulary	words	by	memorizing	word	lists.	Gladys	was	my	star	student	and	I,	too, was	sure	she	would	succeed. Six	months	later,	however,	she	still	could	barely	speak	English.	Her	speech	was hesitant	and	unnatural.	She	constantly	made	grammar	mistakes	with	even	the simplest	sentences.	Her	pronunciation	was	difficult	to	understand.	She	still	thought in	Spanish	and	tried	to	translate	to	and	from	English	when	she	spoke.	Worst	of	all, Gladys	felt	nervous	every	time	she	tried	to	speak	English.	Speaking	English	was	a painful	experience	for	her. Gladys	was	extremely	frustrated.	After	so	much	effort,	she	had	barely	improved. As	her	teacher,	I	too	was	frustrated.	I	was	sure	Gladys	would	improve	quickly	and couldn’t	understand	why	she	had	not.	I	followed	all	of	the	traditional	teaching methods.	I	used	the	standard	textbooks	and	the	standard	classroom	activities.	Gladys was	intelligent,	disciplined	and	consistent,	and	yet	her	English	speaking	barely improved. Sadly,	I	realized	that	Gladys	wasn’t	the	only	one	who	had	not	improved.		Her classmates	also	had	barely	improved.	It	was	frustrating,	and	I	felt	like	a	complete failure	as	a	teacher.		But	when	I	asked	my	colleagues	for	help,	it	turned	out	they	had the	same	problem	–	very	few	of	their	students	were	improving	either!			At	that	point, I	realized	something	was	wrong	–	something	is	wrong	with	standard	methods	for teaching	English.	The	worst	part	for	me	was	that	everyone	accepted	this	situation	as “normal.”	The	other	teachers	didn’t	seem	to	be	concerned	about	their	students’	lack of	progress.	All	the	teachers	were	using	the	same	methods	and	getting	the	same poor	results. In	most	parts	of	the	world,	students	study	English	in	school	for	years.	Yet,	the	vast majority	of	them	never	learn	to	speak	English	well.	After	years	of	study,	they	still have	trouble	with	real	English	conversations.	They	still	feel	nervous	and	shy	about speaking. A	few	years	after	my	experience	with	Gladys,	I	got	a	job	as	an	English	teaching assistant	in	Japan.	I	was	excited	and	eager	to	help	these	young	students	learn	my language.	I	still	remember	my	first	day.	I	was	sitting	at	the	front	of	the	class	next	to the	main	teacher,	who	was	Japanese.	As	the	students	came	into	the	room,	they	saw me	and	giggled	nervously.	They	sat	down	and	continued	to	shyly	glance	up	at	me. They	were	sweet	and	curious. Then	the	class	started.	The	main	teacher	wrote	an	English	sentence	on	the	board.	I don’t	remember	the	exact	sentence,	but	it	was	something	like,	“The	little	girl	goes	to school.”	The	teacher	pointed	to	the	sentence	and	began	to	talk	in	Japanese.	The
students	all	grabbed	their	notebooks	and	began	writing.	Everyone	was	very	serious. Next,	the	teacher	circled	the	word	“goes.”	She	pointed	at	the	word	and	continued speaking	in	Japanese.	She	talked	and	talked	and	talked,	in	Japanese.	The	students wrote	quickly,	filling	their	notebooks	with	information.	Finally,	the	teacher	drew	a line	from	the	word	“goes”	to	the	word	“girl.”	And	then	she	talked	more,	on	and	on and	on,	in	Japanese. This	continued	for	the	entire	class.	The	teacher	drew	lines,	circles,	and	squares. She	used	different	colored	chalk.	And	she	continued	speaking	Japanese. I	was	totally	confused.	I	am	a	native	speaker	of	English,	and	I	was	sitting	in	a beginning	English	class.	Yet	I	could	not	understand	anything	in	the	class	(except	for that	one	sentence).	I	was	thinking	to	myself,	“What	could	this	teacher	possibly	be talking	about	so	much?	It’s	just	one	sentence.”	Yet	the	teacher	spent	an	entire	hour analyzing,	explaining,	and	dissecting	that	one	simple	sentence.	Finally,	at	the	end	of the	class,	the	teacher	asked	me	to	read	the	sentence	aloud	“for	pronunciation.”	I	read the	sentence	a	couple	of	times,	and	that	was	the	only	real	English	input	the	students got	that	day. Sadly,	this	same	pattern	repeated	every	day.	Day	by	day,	I	watched	the	students’ enthusiasm	and	curiosity	disappear.	They	became	bored.	They	became	stressed	and confused.	Every	day	they	wrote	pages	of	notes,	mostly	in	Japanese.	Every	day	the teacher	talked	and	talked	and	talked,	mostly	in	Japanese.	I	couldn’t	understand	why an	English	class	was	being	taught	mostly	in	Japanese.	During	the	average	class,	the students	were	listening	to	Japanese	90%	of	the	time	or	more.	They	heard	very	little English.	No	wonder	they	never	learned	to	speak!	No	wonder	they	were	frustrated and	confused. Honestly,	it	broke	my	heart	to	watch	as	the	school	crushed	these	students’	natural love	of	learning.	It	was	terrible	to	watch	them	grow	bored,	frustrated,	and	stressed. And	six	months	later,	none	of	the	students	could	speak	to	me	at	all,	not	even	the simplest	conversation.	This	kind	of	situation	is	repeated	in	English	classes	all	over the	world. My	experiences	with	Gladys	and	in	Japan	convinced	me	that	traditional	English language	education	is	broken.	I	knew	there	had	to	be	a	better	way	to	help	my students	speak	English	than	what	we	were	doing.	So	I	began	the	search	for	a	better way.	I	devoured	books	about	English	teaching.			I	constantly	tried	out	new	methods in	my	classes.			I	read	research	studies.	I	traveled	and	taught	English	in	other	parts	of the	world. What	surprised	me	was	how	little	the	actual	research	supported	traditional teaching	methods.	As	eminent	University	of	Southern	California	linguist	Stephen
Krashen	noted:	“We	acquire	language	when	we	understand	what	people	tell	us	and what	we	read….there	is	no	need	for	deliberate	memorization.”	If	most	of	us	knew, intuitively,	that	the	best	way	to	learn	English	was	naturally,	I	wondered,	why	were	so many	teachers	and	students	still	choosing	to	use	unnatural,	ineffective	and	old methods	of	teaching? Eventually,	I	went	back	to	school	and	got	a	master’s	degree	in	(TESOL)	Teaching English	to	Speakers	of	Other	Languages.	Along	the	way,	I	did	more	research	and discovered	the	incredible	new	methods	that	would	become	the	basis	for	the Effortless	English™	program. I	also	did	my	own	informal	research.	I	searched	for	excellent	English	speakers who	had	learned	the	language	as	an	adult.	Whenever	I	found	such	a	person,	I interviewed	them.	Over	time,	I	noticed	patterns.	Most	of	these	successful	speakers were	independent	students	who	mastered	spoken	English	outside	of	school.	Most	of them	used	similar	methods,	the	very	same	methods	supported	by	my	master’s research.	Most	avoided	the	traditional	methods	used	in	most	schools. I	changed	my	teaching,	and	when	I	used	these	new	strategies	in	classes,	my students	improved	quickly.	I	couldn’t	believe	it!		They	learned	to	speak	easily	and powerfully.		And	even	better	–	they	were	enjoying	themselves!	After	years	of searching	and	experimentation,	I	had	finally	found	methods	that	worked.
Effortless	English	Today Over	the	years,	I’ve	continued	to	test	and	adapt	these	methods	and	developed	the Effortless	English™	system.	I’ve	organized	the	program	to	include	seven	essential rules	for	learning	English,	which	have	led	countless	students	to	fluency.	To	build	on the	success	of	my	classes,	I	created	audio	courses	and	began	offering	them	online	to English	students	around	the	world.	My	audio	lessons	are	currently	bestsellers	in	25 countries. In	addition,	I	founded	the	Effortless	English	Club™	to	create	an	international English	learning	community	where	students	can	communicate	with	other	members.	I wanted	to	create	an	environment	that	encouraged	confidence	and	success	with English,	because	so	many	learners	struggle	with	nervousness,	shyness,	frustration and	fear	when	speaking.	In	fact,	for	many	people	these	negative	emotions	are	the worst	part	of	speaking	English. In	our	Effortless	English	Club™	students	are	able	to	interact	on	our	forums	and speak	with	each	other	online.	It	is	an	extremely	positive	and	encouraging community,	where	everyone	is	free	to	“play	with	English,”	make	mistakes,	and communicate	without	fear.	In	my	opinion,	we	have	the	best	members	in	the	world.
Every	one	of	our	members	is	focused	not	only	on	their	own	success,	but	also	on helping	other	members	achieve	success	too.	The	result	is	a	supportive	“family”	of learners	and	international	leaders. This	book	is	another	resource	for	students	looking	to	speak	English	powerfully and	fluently.	It	is	designed	to	guide	you	on	the	road	to	fluency,	to	speed	your journey	to	confident,	powerful,	effortless	speaking.	In	this	book,	you	will	learn	how to	re-program	your	negative	emotions	about	English,	develop	confidence	when speaking,	and	follow	a	powerful	and	effective	road	to	fluency.	You’ll	also	learn	how to	use	English	to	improve	your	career	and	achieve	the	success	you	want. Over	the	next	several	chapters,	I	will	describe	the	Effortless	English™	system	in detail,	explain	the	philosophy	behind	it,	and	tell	you	why	both	psychology	and method	are	important	for	language	learning.	I’ll	also	tell	you	exactly	how	to	use	the system	to	reach	your	goals. Join	me	and	enjoy	the	journey.	You	really	have	nothing	to	fear	by	leaving	the	old education	system	behind.	So	let	go	of	the	pressure,	the	stress,	the	fear	and	the boredom.	I	promise	you	this	natural	learning	system	is	fun,	friendly,	and	energetic	– the	opposite	of	most	school	classrooms.	There	is	no	pressure	–	just	friendly encouragement	and	support. Trust	me.	I	have	helped	students	everywhere	in	the	world…	and	now	I	am	eager	to help	you.	I	promise	I	will	always	do	my	best	to	help	you	speak	excellent	English.
	
NOT	LAZY	ENGLISH
So	what	is	Effortless	English™?	By	effortless	I	certainly	dont	mean	lazy English.	On	the	contrary,	effortless	English	is	going	to	be	the	result	of	the	work you	put	in	every	day.	By	following	my	system,	you	will	make	progress	and achieve	the	result	of	speaking	naturally	and	effortlessly	(unforced,	without stress,	hesitation	or	nervousness). In	other	words,	effortless	is	the	result,	not	the	beginning.	Your	goal	is	to speak	English	effortlessly.	You	want	the	words	to	flow	out	without	thinking, without	translating,	without	worry	or	hesitation.	You	want	to	speak	English	just	as you	speak	your	own	native	language.	Effortless	speaking	is	the	final	result,	and sometimes	it	takes	a	lot	of	effort	to	become	effortless!
It	is	possible,	however,	to	thoroughly	enjoy	that	effort.	The	example	I	like	to use	is	that	of	an	athlete	or	artist	in	the	zone.	In	the	zone	means	performing excellently	and	effortlessly.	When	an	athlete	is	in	the	zone	at	one	level,	they	are working	very	hard	–	expending	a	lot	of	energy,	pushing,	totally	focused. However,	when	they	are	enjoying	themselves	and	completely	focused,	the	activity FEELS	effortless	to	them.	There	is	no	feeling	of	forcing,	straining,	etc. In	fact,	the	name	Effortless	English™	was	inspired	by	the	Taoist	idea	of	wu wei	or	effortless	effort.	Its	a	description	of	that	flow	state	where	you	can	be expending	a	lot	of	effort	and	yet	it	feels	totally	effortless	and	natural,	not	forced. So	the	point	is	that	Effortless	English™	is	not	about	laziness,	quick	fixes,	or impossible	scams...	but	rather	about	finding	that	state	of	effortless	effort	or	wu wei.	Effortless	English	means	you	speak	English	fluently.	You	dont	struggle	as you	speak.	You	dont	feel	nervous	or	stressed.	You	dont	think	about	grammar rules	or	translations. When	you	speak	English	effortlessly,	you	communicate	your	ideas	clearly.	You express	your	feelings	powerfully.	You	focus	on	connecting	with	other	people,	not on	conjugating	verbs.	You	thoroughly	enjoy	the	process	of	speaking	English	as you	work,	travel	and	learn.
	
CHAPTER	2 The	Problem	with	Schools
My	teaching	experiences	in	different	parts	of	the	world	convinced	me	that something	is	wrong	with	English	education.	Everywhere	I	went,	it	was	the	same situation.	The	students	were	bored,	frustrated,	stressed,	and	nervous.	Most	students, even	after	years	of	studying	English,	failed	to	speak	the	language	fluently.	You	are not	alone,	because	it’s	a	global	problem. One	of	my	students,	Seiko	from	Japan,	described	this	combination	of	failure	and stress	as	“English	trauma.”	Seiko	said	that	she	hated	English.	She	felt	that	learning English	was	boring	and	stressful	and	speaking	English	was	even	worse.	In	fact,	the thought	of	speaking	to	a	native	speaker	immediately	made	Seiko	feel	extremely nervous	and	shy.	Seiko	felt	she	had	developed	a	psychological	problem	with English	and	had	named	it	“English	trauma.”	A	“trauma”	is	a	deep	wound	or	injury. “How	sad,”	I	thought	to	myself,	“that	so	many	people	now	think	of	English	as	a	kind of	injury	or	mental	disease.” Throughout	my	teaching	career	I’ve	met	many	students	who	had	similar	feelings about	English.	I	discovered	that	Seiko	was	not	alone.	Rather,	“English	trauma”	is	a global	epidemic.	Though	most	people	feel	they	must	learn	to	speak	English,	very few	seem	to	enjoy	it.	Most	who	learn	the	language	struggle	with	the	same	feelings of	nervousness	and	frustration	that	Seiko	had. As	I	encountered	this	problem	more	and	more,	I	began	to	look	for	the	root causes.	I	realized	that	before	I	found	a	solution,	I	needed	to	understand	the	problem. Just	as	a	doctor	must	first	diagnose	a	disease	before	treating	it.	Think	about	it.	What is	the	cause	of	all	this	misery	and	failure?	Why	do	so	many	people	fail	to	speak English	effortlessly	despite	years	of	study?	What	is	wrong	with	English	education? The	first	and	most	obvious	problem	I	found	with	schools	was	the	way	in	which they	teach	English.	Most	schools,	everywhere	in	the	world,	use	the	grammar translation	method.	As	the	name	implies,	the	focus	of	this	method	is	on	grammar analysis	and	the	memorization	of	translated	vocabulary.	This	method	breaks	English into	an	endless	series	of	grammar	formulas	to	memorize.	Of	course,	each	grammar formula	has	exceptions	and	these	must	be	memorized	too. Schools	like	the	grammar	translation	method	because	it	appears	to	be	serious, academic	and	complex.	The	grammar	translation	method	fits	the	way	schools	teach
most	subjects	—	with	textbooks,	lectures,	notes,	memorization,	and	tests.	The	only problem,	as	you	know,	is	that	it	doesn’t	work.	In	real	conversations,	there	simply	is no	time	to	think	about	grammar	formulas	and	their	exceptions.	The	failure	rate	for this	method,	therefore,	is	absolutely	horrible.	Despite	the	failure	of	most	students	to speak	English	fluently,	schools	continue	to	use	this	method.	This	is	an	epic	failure of	our	education	system. Recently,	because	students	find	the	grammar	translation	method	so	boring,	some schools	have	added	“communication	activities”	to	their	curriculum.	Occasionally, the	teacher	puts	the	students	into	pairs	or	groups.	The	students	then	read	or	repeat dialogues	from	a	textbook.	Sometimes	they	might	answer	a	few	questions	from	a worksheet.	Of	course,	these	activities	are	unnatural,	nothing	like	real	English conversation.	Consequently,	the	failure	rate	of	“communication	activities”	is	just	as bad	as	grammar	translation. Obviously	the	English	teaching	methods	used	in	schools	do	not	work.	That	was easy	to	see.	I	knew	it.	The	students	knew	it.	And	many	teachers	know	it	too,	though few	will	admit	it. However,	as	I	continued	to	investigate	the	problem	with	schools,	I	found	even deeper	problems	in	the	education	system.	These	problems	are	less	obvious,	but	in many	ways	far	more	damaging	to	the	students.	I	call	these	problems	“the	hidden curriculum”	because	they	are	the	hidden	lessons	taught	by	schools.
The	Hidden	Curriculum Most	schools,	everywhere	in	the	world,	share	a	similar	hidden	curriculum.	One element	of	this	curriculum	is	student	passivity.	In	schools,	students	are	trained	to	be passive,	not	active.	They	sit	in	chairs,	in	rows.	When	they	are	young,	they	are	told	to be	quiet	and	obey	the	teacher.	As	the	teacher	lectures,	the	students	take	notes.	Later, they	are	told	to	memorize	these	notes	in	preparation	for	a	test.	The	message	is	clear —	learning	is	a	passive	activity.	You	listen	to	the	teacher,	you	take	notes,	you memorize	the	notes. The	problem	is	that	speaking	English	is	not	a	passive	activity.	You	must	connect with	other	people.	You	must	constantly	ask	and	answer	questions.	You	must communicate	ideas,	emotions,	and	descriptions.	You	must	be	ready	for	the unexpected.	You	must	be	spontaneous.	You	must	actively	interact.	English	is	not something	you	passively	study,	it’s	something	you	do. Related	to	the	problem	of	passivity	is	the	issue	of	energy.	Sitting	for	a	long	time is	a	low-energy	activity.	The	longer	you	sit,	the	more	your	energy	drops.	And	as your	energy	drops,	so	does	your	concentration.	What’s	worse,	we	know	that	some
learners	need	physical	movement	in	order	to	learn	effectively.	These	people	are called	“kinesthetic	learners.”	The	truth	is	we	are	all	“kinesthetic	learners”	to	some degree,	because	we	all	benefit	from	physical	movement.	Schools	stick	us	in	chairs and	drain	our	energy.	Eventually,	an	inactive	body	leads	to	an	inactive	mind.
The	One	Right	Answer	Mentality One	of	the	greatest	flaws	of	school	education	is	the	idea	of	“one	right	answer.”	One right	answer	is	a	powerful	part	of	the	hidden	curriculum.	It	is	a	result	of	using textbooks	and	tests. In	school,	you	are	frequently	taught	that	there	is	one,	and	only	one,	correct answer	to	a	question	or	problem.	For	example,	you	may	be	asked	to	choose	the correct	verb	tense	on	a	test,	or	you	may	be	taught	“proper”	English	greetings.	The hidden	message	is	that	the	teacher’s	way	is	always	right. Real	life,	and	real	English,	is	not	this	way.	For	example,	sometimes	I	will	tell	a story	using	the	present	tense,	even	though	the	events	happened	in	the	past.	This	is	a technique	commonly	used	by	native	speakers.	However,	when	English	learners	hear these	stories,	many	are	confused	and	upset.	They	are	convinced	that	the	past	tense	is the	“right	answer”	and	the	only	correct	way	to	tell	the	story.	Some	get	quite	upset and	even	argue	with	me	about	it.	These	students	are	so	convinced	that	there	is	only “one	right	answer”	that	they	will	argue	with	native	speakers! These	students	have	been	trained	to	believe	that	there	is	only	one	correct	way	to say	things	in	English.	The	truth	is	there	are	always	many	ways	to	say	the	same	thing. We	can	change	verb	tenses	in	order	to	change	the	feeling	of	the	story.	We	can	use different	vocabulary	and	different	phrases.	And	we	even	break	grammar	rules	all the	time!	‘One	right	answer’	thinking	limits	and	confuses	English	learners.	Effective communication	requires	flexibility	while	the	“one	right	answer”	mentality	trains students	to	be	rigid	and	unimaginative. Connected	to	this	problem	is	another	dangerous	part	of	the	hidden	curriculum	— fear	of	mistakes.	This	is	one	of	the	most	negative	and	traumatizing	messages	taught in	schools.	How	is	the	fear	of	mistakes	taught?	Through	tests	and	corrections.	In nearly	every	school	all	over	the	world,	teachers	regularly	give	quizzes	and	tests. The	teacher	asks	questions	and	the	students	must	provide	the	one	right	answer.	Of course,	the	one	right	answer	is	always	the	teacher’s	answer. What	happens	if	the	student	provides	a	different	answer?	They	are	punished	with	a lower	score.	Students	are	smart,	and	they	quickly	understand	that	in	school,	mistakes are	bad	and	must	be	avoided.	They	also	understand	that	truth	is	unimportant	and	the best	way	to	succeed	is	to	simply	give	the	answer	that	the	teacher	wants.	Even	worse
is	when	a	student,	already	feeling	nervous,	tries	to	speak	English	with	the	whole class	listening.	They	are	just	learning,	so	of	course	they	will	make	mistakes.	When the	teacher	corrects	these	mistakes,	the	student	is	embarrassed	and	becomes	even more	nervous.	Eventually,	most	students	try	to	avoid	speaking	English	because	the situation	is	so	painful. By	punishing	and	correcting	mistakes,	schools	punish	risk	taking.	Little	by	little, they	train	students	to	avoid	risk	and	avoid	doing	anything	they	can’t	do	perfectly.	Yet there	is	no	perfection	with	English	speaking.	Even	native	speakers	make	mistakes. We	make	grammar	mistakes.	We	mispronounce	words.	We	forget	vocabulary words.	It	doesn’t	matter,	because	we	are	focused	on	communicating,	not	on	tests	and grades. Of	course,	the	fear	of	mistakes	goes	far	beyond	English	class.	After	years	of school,	most	people	learn	to	avoid	risk	in	most	parts	of	their	life.	School	trains them	to	be	passive,	rigid,	timid,	and	obedient.	This	not	only	hurts	your	English speaking,	it	also	harms	your	career	and	limits	your	success	in	all	areas	of	life. Fortune	favors	the	bold.	Those	who	are	active,	flexible,	and	passionate	are	the	ones who	achieve	the	greatest	success	in	life.	The	passive	and	obedient	rarely	live	their dreams. You	will	make	many	mistakes	as	you	improve	your	English	speaking.	There	is	no need	to	be	upset	by	this.	The	truth	is,	most	native	speakers	don’t	care.	They	don’t care	if	you	make	grammar	mistakes.	They	just	want	to	communicate	with	you.	They want	to	share	thoughts,	ideas	and	feelings.	They	want	to	communicate	with	you	as	a human	being,	not	as	an	“English	student.”	To	communicate	effectively,	you	must forget	the	idea	of	perfection	and	learn	to	be	flexible.
The	Dirty	Secret	of	English	Teaching If	the	hidden	curriculum	is	so	bad,	why	do	schools	and	teachers	continue	to	follow it?	The	truth	about	our	education	system	is	that	the	curriculum	exists	to	benefit	the schools,	not	the	students.	Teachers	use	these	methods	because	they	are	easier	for	the teacher,	not	because	they	are	good	for	the	student.	The	hidden	curriculum	creates passive	students.	It	creates	obedient	students.	Passive	and	obedient	students	are	easier to	control,	making	life	easier	for	teachers	and	school	administrators. Textbooks,	for	example,	make	the	teacher’s	job	much	easier.	By	using	a	textbook, the	teacher	doesn’t	have	to	plan	new	lessons	for	every	class.	Planning	lessons	is hard	work,	and	a	textbook	makes	it	much	easier.	The	teacher	can	simply	follow	the textbook	with	minimum	effort.	Many	teachers	are	little	more	than	textbook	readers. Every	day	they	read	the	textbook	to	their	students,	slavishly	following	the	lessons.	In
my	opinion,	they	can	barely	be	called	“teachers”	at	all.	Perhaps	we	should	call	them “textbook	readers”	instead. Another	benefit	of	textbooks,	for	the	schools,	is	that	they	standardize	learning.	By using	a	textbook,	the	school	ensures	that	every	English	class	is	learning	exactly	the same	thing.	School	officials	like	this	because	it	makes	testing	and	ranking	students easier.	Schools	are	like	factories,	the	bosses	want	everything	to	be	the	same. The	same	is	true	for	tests	and	grades.	These	provide	little	to	no	benefit	to	English learners.	In	fact,	as	we	have	discussed,	tests	and	grades	increase	stress	and	create	a fear	of	making	mistakes.	Tests	and	grades	are	a	primary	cause	of	“English	trauma.” On	the	other	hand,	tests	and	grades	are	a	powerful	tool	of	control	for	teachers. When	students	fear	bad	grades,	they	obey	the	teacher	more.	They	learn	that	the teacher	is	always	right,	because	if	they	don’t	agree	with	the	teacher’s	answer	they are	punished	with	lower	scores. Grades	are	a	means	of	ranking	students.	Most	teachers	and	administrators	are focused	on	ranking	students	rather	than	helping	all	succeed.	In	many	schools,	the official	policy	is	that	a	certain	percentage	of	students	in	every	class	must	get	poor grades,	a	certain	percentage	must	get	“medium	level”	grades,	and	only	a	small percentage	can	be	given	excellent	grades.	In	other	words,	the	system	is	designed	to create	failure	for	a	large	number	of	students. While	working	at	a	university	in	Thailand,	I	was	told	directly	by	my	boss	that	too many	of	my	students	had	high	scores.	My	boss	insisted	that	I	fail	more	students	in my	class.	I	was	shocked	and	angry.	I	quit	the	job	rather	than	purposely	fail	dedicated students.	Sadly,	this	mentality	of	“designing	for	failure”	is	present	in	most	school everywhere	in	the	world.	Schools	benefit	from	ranking	and	controlling	students. The	grammar	translation	method	also	benefits	the	teacher	but	not	the	student.	By teaching	grammar	rules,	the	teacher	can	simply	lecture	from	the	textbook.	Because linguistics	is	a	complicated	subject,	the	teacher	appears	knowledgeable	and	thus establishes	a	position	of	superiority	over	the	students.	Even	if	the	teacher	is	a	nonnative	speaker	with	terrible	English	ability,	he	or	she	can	pretend	to	be	an	expert	by teaching	complex	grammar	from	a	book.	The	shocking	truth	is	that	many	nonnative	English	teachers,	in	fact,	speak	English	very	poorly.	By	focusing	on grammar	they	disguise	their	inability	to	speak	well. What	about	communication	activities?	Surely	they	are	designed	to	help	students. Actually,	they	are	not.	These	activities,	as	we	discussed	previously,	are	unnatural. They	are	nothing	like	a	real	conversation,	and	thus	do	not	prepare	students	to	have real	conversations.	However,	communication	activities	are	great	for	teachers.	The teacher	puts	the	students	into	pairs	or	groups	and	asks	them	to	follow	a	textbook
activity.	Often,	the	students	simply	read	a	written	dialogue	from	the	book	or	answer pre-written	questions	from	the	book.	The	advantage	for	the	teacher	is	that	once	such an	activity	is	started,	the	teacher	can	rest	and	do	nothing.	While	the	students	go through	the	textbook	activity,	the	teacher	relaxes.	It’s	a	secret	among	English teachers	that	communication	activities	are	a	great	way	to	waste	time	and	avoid	work. One	particularly	horrible	version	of	communication	activities	is	the	use	of movies.	Used	correctly,	movies	can	be	a	powerful	English	learning	tool.	Most teachers,	however,	simply	use	movies	as	a	way	to	waste	time.	They	put	in	a	movie, turn	out	the	lights,	and	push	play.	For	the	remainder	of	the	class,	the	teacher	happily does	nothing.	The	students	are	usually	happy,	too,	because	watching	a	movie	is	far more	interesting	than	grammar,	even	if	they	can’t	understand	most	of	the	film.
Passive	Low	Energy	Benefits	the	Teacher Finally,	let’s	look	at	the	low	energy	situation	in	most	schools.	From	childhood, students	are	forced	to	sit	for	hours,	motionless	in	chairs.	They	are	told	to	be	quiet and	obedient.	By	adulthood,	most	people	are	thoroughly	trained.	They	accept passive	lectures	and	low	energy	as	a	normal	part	of	learning. Why	would	schools	and	teachers	want	low	energy?	Again,	because	low	energy students	are	easier	to	manage.	A	teacher	must	work	much	harder	with	curious, energetic	students.	Sadly,	most	teachers	prefer	the	easy	way.	It’s	much	easier	for them	to	lecture	quietly	to	passive	students. The	truth	is	that	many	teachers	are	tired	and	stressed.	Because	of	this,	they constantly	look	for	ways	to	make	their	own	job	easier.	Their	first	concern	is	not	the students.	They	are	not	obsessively	focused	on	getting	better	results	for	the	learners. Rather,	they	just	want	to	get	through	their	workday	as	easily	as	possible.	There	are many	reasons	for	this	situation,	but	the	end	result	for	the	student	is	boredom, frustration,	and	poor	results. This	is	the	ugly	truth	of	education.	This	is	the	reason	you	cannot	speak	English well,	despite	years	of	study.	This	is	the	reason	you	find	English	to	be	stressful, difficult,	and	boring.	This	is	the	cause	of	English	trauma.	This	is	the	source	of	the problem. Happily,	there	is	a	solution.	The	Internet	has	made	independent	learning	easy	for all.	No	matter	where	you	live	or	what	you	do,	it	is	possible	to	master	spoken English	without	schools.	All	you	need	is	an	Internet	connection! In	the	next	chapter,	I	will	introduce	the	solution	to	English	trauma.	You	will	learn how	to	heal	and	how	to	finally	get	the	results	you	want	with	English	speaking.";
        ScrabbleScore.Score(testBigText);
    }

    [Fact(Skip="1")]
    public void Lowercase_letter()
    {
        Assert.Equal(1, ScrabbleScore.Score("a"));
    }

    [Fact(Skip="1")]
    public void Uppercase_letter()
    {
        Assert.Equal(1, ScrabbleScore.Score("A"));
    }

    [Fact(Skip="1")]
    public void Valuable_letter()
    {
        Assert.Equal(4, ScrabbleScore.Score("f"));
    }

    [Fact(Skip="1")]
    public void Short_word()
    {
        Assert.Equal(2, ScrabbleScore.Score("at"));
    }

    [Fact(Skip="1")]
    public void Short_valuable_word()
    {
        Assert.Equal(12, ScrabbleScore.Score("zoo"));
    }

    [Fact(Skip="1")]
    public void Medium_word()
    {
        Assert.Equal(6, ScrabbleScore.Score("street"));
    }

    [Fact(Skip="1")]
    public void Medium_valuable_word()
    {
        Assert.Equal(22, ScrabbleScore.Score("quirky"));
    }

    [Fact(Skip="1")]
    public void Long_mixed_case_word()
    {
        Assert.Equal(41, ScrabbleScore.Score("OxyphenButazone"));
    }

    [Fact(Skip="1")]
    public void English_like_word()
    {
        Assert.Equal(8, ScrabbleScore.Score("pinata"));
    }

    [Fact(Skip="1")]
    public void Empty_input()
    {
        Assert.Equal(0, ScrabbleScore.Score(""));
    }

    [Fact(Skip="1")]
    public void Entire_alphabet_available()
    {
        Assert.Equal(87, ScrabbleScore.Score("abcdefghijklmnopqrstuvwxyz"));
    }
}